---
 - hosts: mhost1
   become:
   tasks:
         - name: Adding firewall rule
           firewalld:
                 port: 80/tcp
                 state: enabled
                 permanent: yes
           notify: Reload firewall
   handlers:
         - name: Reload firewall
           systemd:
                 name:  firewalld 
                 state: reloaded
